service: coffeeMustacheBackend

provider:
  name: aws
  runtime: provided.al2
  region: ap-south-1
  stage: ${opt:stage}
  environment: ${file(env.json)}
  httpApi:
    cors: true

functions:
  HealthCheck:
    handler: bootstrap
    events:
      - http:
          path: /ping
          method: GET
          cors: true

  SendOtp:
    handler: bootstrap
    events:
      - http:
          path: /sendOtp
          method: POST
          cors: true

  VerifyOtp:
    handler: bootstrap
    events:
      - http:
          path: /verifyOtp
          method: POST
          cors: true

  UpsellItem:
    handler: bootstrap
    events:
      - http:
          path: /upsellItem
          method: POST
          cors: true

  CrossSellItem:
   handler: bootstrap
   events:
     - http:
         path: /crossSellItem
         method: POST
         cors: true

  GetUpsellAndCrossSell:
   handler: bootstrap
   events:
     - http:
         path: /getUpsellAndCrossSell
         method: POST
         cors: true
  
  AskMenuAI:
   handler: bootstrap
   events:
     - http:
         path: /askMenuAI
         method: POST
         cors: true

  GetMenu:
   handler: bootstrap
   events:
     - http:
         path: /getMenu
         method: POST
         cors: true

  GetFilteredList:
   handler: bootstrap
   events:
     - http:
         path: /getFilteredList
         method: POST
         cors: true

  CreateCuratedCartsJob:
    handler: bootstrap
    environment:
      FUNCTION_NAME: "curatedCartCronJob"
    events:
      - schedule:
          rate: cron(30 1 * * ? *)  # Runs every day at 1:30 AM UTC
          enabled: true

  