service: coffeeMustacheBackendDev

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1
  stage: ${opt:stage}
  environment: ${file(envDev.json)}
  httpApi:
    cors: true

functions:
  HealthCheck:
    handler: bootstrap
    events:
      - http:
          path: /ping
          method: GET
          cors: true

  UpsellItem:
    handler: bootstrap
    events:
      - http:
          path: /upsellItem
          method: POST
          cors: true

  GetUpsellAndCrossSell:
   handler: bootstrap
   events:
     - http:
         path: /getUpsellAndCrossSell
         method: POST
         cors: true
  
  AskMenuAI:
   handler: bootstrap
   timeout: 30
   events:
     - http:
         path: /askMenuAI
         method: POST
         cors: true

  GetMenu:
   handler: bootstrap
   events:
     - http:
         path: /getMenu
         method: POST
         cors: true

  GetFilteredList:
   handler: bootstrap
   events:
     - http:
         path: /getFilteredList
         method: POST
         cors: true

  CreateCuratedCartsJob:
    handler: bootstrap
    timeout: 300
    environment:
      FUNCTION_NAME: "curatedCartCronJob"
    events:
      - http:
          path: /curatedCartCronJob
          method: GET
          cors: true
      - schedule:
          rate: cron(5 0 * * ? *)  # Runs every day at 12:05 AM UTC
          enabled: true

  GetCrossSellData:
    handler: bootstrap
    timeout: 30
    events:
      - http:
          path: /getCrossSellData
          method: POST
          cors: true
      - schedule:
          rate: rate(2 minutes)  # Keeps the Lambda warm
          enabled: true
          input:
            base_item_id: 0
            cart_id: "keep-warm"

  GetCuratedCart:
    handler: bootstrap
    events:
      - http:
          path: /getCuratedCart
          method: POST
          cors: true

  RecordUserSession:
    handler: bootstrap
    events:
      - http:
          path: /recordUserSession
          method: POST
          cors: true

  AddToCartRequest:
    handler: bootstrap
    events:
      - http:
          path: /addToCart
          method: POST
          cors: true

  GetCart:
    handler: bootstrap
    events:
      - http:
          path: /getCart
          method: POST
          cors: true

  UpdateCustomizations:
    handler: bootstrap
    events:
      - http:
          path: /updateCustomizations
          method: POST
          cors: true

  UpdateCrossSellItems:
    handler: bootstrap
    events:
      - http:
          path: /updateCrossSellItems
          method: POST
          cors: true

  UpdateQuantity:
    handler: bootstrap
    events:
      - http:
          path: /updateQuantity
          method: POST
          cors: true

  GetCheckoutCrossSells:
    handler: bootstrap
    events:
      - http:
          path: /crossSellCheckout
          method: POST
          cors: true

  UpgradeCart:
    handler: bootstrap
    events:
      - http:
          path: /upgradeCart
          method: POST
          cors: true

  GetItemAudio:
    handler: bootstrap
    events:
      - http:
          path: /getItemAudio
          method: POST
          cors: true

  PlaceOrder:
    handler: bootstrap
    events:
      - http:
          path: /placeOrder
          method: POST
          cors: true

  FetchOrderDetails:
    handler: bootstrap
    events:
      - http:
          path: /fetchOrderDetails
          method: POST
          cors: true

  InvalidateSession:
    handler: bootstrap
    events:
      - http:
          path: /invalidateSession
          method: POST
          cors: true

  GetFeedbackForm:
    handler: bootstrap
    events:
      - http:
          path: /getFeedbackForm
          method: POST
          cors: true

  SubmitFeedback:
    handler: bootstrap
    events:
      - http:
          path: /submitFeedback
          method: POST
          cors: true

  CallWaiter:
    handler: bootstrap
    events:
      - http:
          path: /callWaiter
          method: POST
          cors: true

  CheckSessionStatus:
    handler: bootstrap
    events:
      - http:
          path: /checkSessionStatus
          method: POST
          cors: true

  GetCafeDetails:
    handler: bootstrap
    events:
      - http:
          path: /getCafeDetails
          method: POST
          cors: true

  AddSpecialRequest:
    handler: bootstrap
    events:
      - http:
          path: /addSpecialRequest
          method: POST
          cors: true

  AcceptTermsAndConditions:
    handler: bootstrap
    events:
      - http:
          path: /acceptTermsAndConditions
          method: GET
          cors: true

  RecordUserAdClick:
    handler: bootstrap
    events:
      - http:
          path: /recordUserAdClick
          method: POST
          cors: true

  GetProfile:
    handler: bootstrap
    events:
      - http:
          path: /getProfile
          method: GET
          cors: true


  

  